/**
 * babyjub.ts — BabyJubJub scalar multiplication.
 *
 * The spend public key in the Menoid register/user-commitment scheme is a real
 * curve point: pk = sk · Base8 on BabyJubJub (the twisted Edwards curve over
 * BN254's scalar field). The extension gets this from circomlibjs; that package
 * is large, slow to boot and drags in a WASM/asm build, so the curve is
 * implemented here directly — it is only ~60 lines of field arithmetic.
 *
 * Twisted Edwards:  a·x² + y² = 1 + d·x²·y²
 *
 * Points are held in extended coordinates (X, Y, Z, T) with x = X/Z, y = Y/Z
 * and T = X·Y/Z, so the ladder needs no modular inversion — one inversion at
 * the very end converts back to affine. Verified against circomlibjs (see
 * scripts/verify-babyjub.mjs).
 */

/** BN254 scalar field prime — the field BabyJubJub is defined over. */
export const BABYJUB_P =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n;

/** Order of the prime-order subgroup generated by Base8. */
export const BABYJUB_SUBGROUP_ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n;

const A = 168700n;
const D = 168696n;

/** The generator of the prime-order subgroup (circomlibjs `Base8`). */
export const BASE8: readonly [bigint, bigint] = [
  5299619240641551281634865583518297030282874472190772894086521144482721001553n,
  16950150798460657717958625567821834550301663161624707787222815936182638968203n,
];

const mod = (a: bigint): bigint => {
  const r = a % BABYJUB_P;
  return r < 0n ? r + BABYJUB_P : r;
};

/** Modular inverse via the extended Euclidean algorithm. */
function inv(a: bigint): bigint {
  let [old_r, r] = [mod(a), BABYJUB_P];
  let [old_s, s] = [1n, 0n];
  while (r !== 0n) {
    const q = old_r / r;
    [old_r, r] = [r, old_r - q * r];
    [old_s, s] = [s, old_s - q * s];
  }
  if (old_r !== 1n) throw new Error("babyjub: value is not invertible");
  return mod(old_s);
}

type Ext = { X: bigint; Y: bigint; Z: bigint; T: bigint };

const IDENTITY: Ext = { X: 0n, Y: 1n, Z: 1n, T: 0n };

const toExt = ([x, y]: readonly [bigint, bigint]): Ext => ({
  X: mod(x),
  Y: mod(y),
  Z: 1n,
  T: mod(x * y),
});

/** Unified addition for extended twisted Edwards coordinates (add-2008-hwcd). */
function add(p: Ext, q: Ext): Ext {
  const a = mod(p.X * q.X);
  const b = mod(p.Y * q.Y);
  const c = mod(D * p.T * q.T);
  const d = mod(p.Z * q.Z);
  const e = mod((p.X + p.Y) * (q.X + q.Y) - a - b);
  const f = mod(d - c);
  const g = mod(d + c);
  const h = mod(b - A * a);
  return { X: mod(e * f), Y: mod(g * h), Z: mod(f * g), T: mod(e * h) };
}

/** Constant-iteration double-and-add. Not constant-TIME — see note below. */
function mul(point: Ext, scalar: bigint): Ext {
  let acc = IDENTITY;
  let base = point;
  let k = scalar;
  while (k > 0n) {
    if (k & 1n) acc = add(acc, base);
    base = add(base, base);
    k >>= 1n;
  }
  return acc;
}

/**
 * sk · Base8, returned affine as decimal strings (circomlibjs' representation).
 *
 * NOTE ON SIDE CHANNELS: the ladder above branches on secret bits, so it is not
 * constant-time. That matches circomlibjs (which is also variable-time) and is
 * acceptable here because this runs once, locally, on the user's own device
 * against their own key — there is no remote timing observer. Do not reuse this
 * for anything that multiplies an attacker-chosen scalar in a shared process.
 */
export function mulPointBase8(scalar: bigint): { x: string; y: string } {
  const sk = ((scalar % BABYJUB_SUBGROUP_ORDER) + BABYJUB_SUBGROUP_ORDER) % BABYJUB_SUBGROUP_ORDER;
  if (sk === 0n) return { x: "0", y: "1" };
  const r = mul(toExt(BASE8), sk);
  const zInv = inv(r.Z);
  return { x: mod(r.X * zInv).toString(), y: mod(r.Y * zInv).toString() };
}
